---
- name: Build Flask Docker image.
  docker_image:
    name: "flask"
    tag: "latest"
    source: build
    build:
      path: "/home/ubuntu/www"
      pull: false
    state: present

- name: Run Flask Docker container.
  docker_container:
    image: flask:latest
    name: www
    state: started
    command: python3 /opt/www/app.py
    ports: "80:80"