---
- hosts: appserver
  become: true

  vars_files:
    - ../../vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Add Ubuntu user to docker group.
      user:
        name: ubuntu
        groups: docker
        append: true

    - name: Install Pip.
      apt: name=python3-pip state=present

    - name: Install Docker Python library.
      pip: name=docker state=present

    - name: Copy Flask folder into place for Docker build.
      copy:
        src: www
        dest: /home/vagrant

    - name: Copy Flask app into place.
      template:
        src: app.py.j2
        dest: /home/vagrant/www/app.py
        mode: 0755
      with_items:
        - "{{ mysql_users }}"

    - name: Build Flask Docker image.
      docker_image:
        name: "flask"
        tag: "latest"
        source: build
        build:
          path: "/home/vagrant/www"
          pull: false
        state: present

    - name: Run Flask Docker container.
      docker_container:
        image: flask:latest
        name: www
        state: started
        command: python3 /opt/www/app.py
        ports: "80:80"
